Creación y Indexación:


Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5. -->



In [1]:
import numpy as np

In [ ]:
array_1d = np.random.randint(10,100, 50)
print(array_1d)

[45 95 23 43 59 81 95 34 17 25 62 34 68 86 86 52 21 47 20 96 98 41 91 80
 23 35 44 69 94 94 95 58 88 80 83 13 30 91 18 37 49 55 68 77 42 16 21 63
 94 78]


In [16]:
np.where(array_1d % 5 == 0,)

#np.where(a_2d_2 > 30, 100, -100)


(array([ 0,  1,  6,  9, 18, 23, 25, 30, 33, 36, 41]),)

In [17]:
array_1d.size




50

In [10]:
import numpy as np

# 1. Crear el array 1D
array_1d = np.random.randint(10, 100, 50) 
print(f"Array original (primeros 10): {array_1d[:10]}...")

# 2. Generar y filtrar los índices
indices = np.arange(len(array_1d))
mascara_indices = (indices % 5 == 0)

# 3. Acceder a los elementos en esas posiciones
elementos_seleccionados = array_1d[mascara_indices]

print("\nÍndices seleccionados: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45]")
print(f"Elementos en esas posiciones: {elementos_seleccionados}")

Array original (primeros 10): [16 16 53 20 60 53 40 14 39 35]...

Índices seleccionados: [0, 5, 10, 15, 20, 25, 30, 35, 40, 45]
Elementos en esas posiciones: [16 53 92 12 31 49 44 81 66 91]


Crea un array 1D con 30 valores aleatorios del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.



In [34]:
#array_1d = np.random.randint(10,100, 50)
array_1d_2 = np.random.randint(1,21,30)
print(array_1d_2)

array_1d_2[0::2]

[ 9 13  5  8  7 20  4 17  1 10 19  9  7  1  9  5 14  4  2 10  6  7  9 17
 10 10  9  5  9 13]


array([ 9,  5,  7,  4,  1, 19,  7,  9, 14,  2,  6,  9, 10,  9,  9],
      dtype=int32)

In [27]:
array_1d_2.size

30

Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [42]:
array_2d_albondiga = np.random.randint(1,50, (4,6))
print(array_2d_albondiga)

[[ 8 15  8  3 30 30]
 [41 13 46 18  7 42]
 [ 4 39 10 32 32 32]
 [31 48  3  4  4 25]]


In [ ]:
#operaciones entre arrays

array_2d_salsa = np.random.sample(size=(4,6))

In [46]:
print(array_2d_salsa)

[[0.66591115 0.79907604 0.86543443 0.36154108 0.78735484 0.44178464]
 [0.52884179 0.37078648 0.74270103 0.68709864 0.35745882 0.82866719]
 [0.92476142 0.23404187 0.7473677  0.54173491 0.70537682 0.58087754]
 [0.83793164 0.65850552 0.18555716 0.68198756 0.93819133 0.20937687]]


In [44]:
espaguetis = array_2d_albondiga + array_2d_salsa

In [45]:
print(espaguetis)

[[ 8.66591115 15.79907604  8.86543443  3.36154108 30.78735484 30.44178464]
 [41.52884179 13.37078648 46.74270103 18.68709864  7.35745882 42.82866719]
 [ 4.92476142 39.23404187 10.7473677  32.54173491 32.70537682 32.58087754]
 [31.83793164 48.65850552  3.18555716  4.68198756  4.93819133 25.20937687]]


In [47]:
espaguetis[-1]

array([31.83793164, 48.65850552,  3.18555716,  4.68198756,  4.93819133,
       25.20937687])