¿Qué diferencia hay entre una Serie y un DataFrame?
Es el turno de los DataFrames

- Crea un array de dos dimensiones con 4 filas y 3 columnas.
- Convierte el array en un DataFrame donde las columnas se llamen "España", "Francia" e "Italia".

In [1]:
import pandas as pd
import numpy as np

In [2]:
array_2D = np.zeros(shape=(4,3))

In [3]:
print(array_2D)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
columnas = ["italia", "francia", "españa"]

In [5]:
df = pd.DataFrame(data = array_2D, columns= columnas)

In [6]:
df

italia  francia  españa
0     0.0      0.0     0.0
1     0.0      0.0     0.0
2     0.0      0.0     0.0
3     0.0      0.0     0.0

- Descarga el archivo "medallas" y carga el DataFrame.
- Usando el loc extrae todas las columnas de la fila de Tailandia.
- Usando el loc extrae todas las columnas de China e Irán.
- Usando el loc extrae solo las columnas de "Oro", "Plata" y "Bronce" de China e Irán.
- Usando el iloc extrae la información de la India. Devolved todas las columnas.
- Usando el iloc extrae todas las columnas de los países que estén en posición impar. La primera que nos tendría que salir es Japón y la última Corea del Norte.

In [9]:
df_medallas = pd.read_csv("medallas.csv", index_col = 0)

In [10]:
df_medallas

País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235

In [14]:
df_medallas.loc[7]

País      Tailandia
Oro             132
Plata           175
Bronce          278
Name: 7, dtype: object

In [26]:
df_medallas.loc[[1,4],['Oro','Plata','Bronce']]

Oro  Plata  Bronce
1  1473    994     720
4   179    181     197

In [34]:
masc = df_medallas["País"] == "India"
df_medallas.iloc[list(masc)]

País  Oro  Plata  Bronce
6  India  154    202     315

In [36]:
df_medallas.loc[masc]

País  Oro  Plata  Bronce
6  India  154    202     315

In [39]:
df_medallas[masc].index[0]-1

np.int64(5)

In [40]:
df_medallas.iloc[df_medallas[masc].index[0]-1]

País      India
Oro         154
Plata       202
Bronce      315
Name: 6, dtype: object

In [41]:
df_medallas.index

Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype='int64')

In [27]:
df_medallas.iloc[5]

País      India
Oro         154
Plata       202
Bronce      315
Name: 6, dtype: object

In [35]:
df_medallas

País   Oro  Plata  Bronce
1             China  1473    994     720
2             Japón  1032   1037     985
3     Corea del Sur   745    663     827
4              Irán   179    181     197
5        Kazajistán   155    158     224
6             India   154    202     315
7         Tailandia   132    175     278
8         Indonesia   112    131     240
9      China Taipéi    99    144     276
10  Corea del Norte    91    120     235

In [42]:
df_medallas.reset_index()

index             País   Oro  Plata  Bronce
0      1            China  1473    994     720
1      2            Japón  1032   1037     985
2      3    Corea del Sur   745    663     827
3      4             Irán   179    181     197
4      5       Kazajistán   155    158     224
5      6            India   154    202     315
6      7        Tailandia   132    175     278
7      8        Indonesia   112    131     240
8      9     China Taipéi    99    144     276
9     10  Corea del Norte    91    120     235

Utilizando el código del ejercicio anterior, selecciona unicamente las columnas "Oro", "Plata" y "Bronce".

Contesta a las siguientes preguntas:

¿Qué país consiguió más de 200 medallas de oro?

¿Qué país consiguió más de 200 medallas de oro y más de 1000 de plata?

¿Qué país consiguió más de 200 medallas de oro o más de 700 de bronce?

Crea una nueva columna que se llame "total" que sea el resultado de la suma de todas las medallas obtenidas por cada país.